blank_issues_enabled: false
contact_links:
  - name: Functional issues❓
    url: https://jq.qq.com/?_wv=1027&k=Y2vdUpII
    about: Have questions about Gh-Robots features? Welcome to join our QQ exchange group! 😍
